# Generated by Django 3.0.8 on 2020-12-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citizen',
            old_name='Avatar',
            new_name='avatar',
        ),
        migrations.AddField(
            model_name='citizen',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='citizen',
            name='birth_day',
            field=models.DateField(default='1900-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citizen',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=15),
        ),
        migrations.AddField(
            model_name='citizen',
            name='rank',
            field=models.CharField(default='', max_length=100),
        ),
    ]
