# Generated by Django 3.0.8 on 2020-11-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='Surname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
