# Generated by Django 3.0.8 on 2020-11-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citizen',
            old_name='Avatar',
            new_name='avatar',
        ),
        migrations.RemoveField(
            model_name='citizen',
            name='user',
        ),
        migrations.AddField(
            model_name='citizen',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='citizen',
            name='birth_day',
            field=models.DateField(default='1900-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citizen',
            name='email',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citizen',
            name='first_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citizen',
            name='gender',
            field=models.CharField(default='Other', max_length=15),
        ),
        migrations.AddField(
            model_name='citizen',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='citizen',
            name='password',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
