# Generated by Django 3.0.8 on 2020-11-30 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0002_auto_20201201_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='rank',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=15),
        ),
    ]
