# Generated by Django 3.0.8 on 2020-11-30 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0002_citizen_surname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citizen',
            old_name='Avatar',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='citizen',
            old_name='Surname',
            new_name='surname',
        ),
    ]
