# Generated by Django 3.0.8 on 2020-12-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0002_auto_20201202_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='cult_projects',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='citizen',
            name='ed_projects',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='citizen',
            name='health_projects',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='citizen',
            name='military_projects',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='citizen',
            name='social_projects',
            field=models.IntegerField(default=0),
        ),
    ]
