# Generated by Django 3.0.8 on 2020-11-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0004_citizen_birth_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='gender',
            field=models.CharField(default='Other', max_length=15),
        ),
    ]
