# Generated by Django 3.0.8 on 2020-12-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0004_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
