# Generated by Django 3.0.8 on 2020-12-13 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0005_citizen_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('photo', models.ImageField(upload_to='project photos')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Content.Project')),
            ],
            options={
                'verbose_name': 'Project photo',
                'verbose_name_plural': 'Project photos',
            },
        ),
    ]
