# Generated by Django 3.0.8 on 2020-11-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0005_citizen_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
