# Generated by Django 3.0.8 on 2020-12-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0006_projectphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectphoto',
            name='photo',
            field=models.ImageField(upload_to='project_photos'),
        ),
    ]
