# Generated by Django 3.0.8 on 2020-12-16 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0007_auto_20201217_0345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citizen',
            old_name='cult_projects',
            new_name='culture_projects',
        ),
        migrations.RenameField(
            model_name='citizen',
            old_name='ed_projects',
            new_name='education_projects',
        ),
        migrations.RenameField(
            model_name='citizen',
            old_name='health_projects',
            new_name='healthcare_projects',
        ),
    ]
